export enum ConferenceDetails {
    ON_MUTE = "Sorry, I didn't realise I was on mute.",
    TAKE_OFFLINE = "Can we take this offline?",
    LOOP_IN = "Just wanted to loop you in.",
    PLEASE_MUTE = "Can everyone mute themselves?",
    WAITING_ON_HOST = "Waiting for host to start the meeting.",
    CHILDREN = "*Children noises in the background*",
    ANOTHER_CALL = "Have to hop on another call.",
    SCREEN_SHARE = "Do you see my screen?",
    PUSH_BACK = "Can we push this meeting back ___ minutes.",
    FOLLOW_UP = "I'll have to get back to you.",
    OVERSHARING = "You're still sharing your screen.",
    AGGRESSIVE_KEYBOARD = "*Loud keyboard typing*",
    SWITCH_HEADPHONES = "Hold on. Let me switch out my headphones.",
    QUESTION_SILENCE = "I want to stop hear for any questions.",
    AWKWARD_SILENCE = "Don't all speak at once!",
    INTERRUPTION = "*Interruption* Sorry, you go ahead*",
    ANIMALS = "*Animal noises in the background*",
    WAIT_FOR_SOMEONE = "Let's wait for ___ to join the call.",
    CONFERENCE_ID = "Couldn't find the conference ID for the meeting",
    LETS_GET_STARTED = "We have enough people now. Let's start on the agenda.",
    GOODBYES = "*Everyone saying goodbye at the end of the meeting*",
    TECHNICAL_DIFFICULTIES = "*Echo, feeback or bad connection*",
    TIME_RUNNING_OUT = "There's only ___ minutes left in the meeting",
    CAN_YOU_HEAR = "Can you guys hear me?",
    LOST = "Oops, it looks like we've lost ___"
};